COL_COSTS = 'costs'
COL_DATE = 'date'
COL_DS = 'ds'
COL_Y = 'y'
COL_CUMSUM = 'cumsum'
COLS2EXTRACT = [COL_DATE, COL_COSTS]
COLSDESTINATION = [COL_DS, COL_Y, COL_CUMSUM]

COL_Y_LABEL = 'Expenses'
COL_DS_LABEL = 'Time'
